### ISSUE TITLE
v1.8.1 not building with Kotlin 1.9.20.*

### ISSUE THREAD

**Issue by chrisbanes** [Foso/Ktorfit#459]
### Ktorfit version

1.8.1

### What happened and how can we reproduce this issue?

With 1.8.1 the error from #434 seems to be back when using Kotlin 1.9.20-beta02 (or rc01). If I stick with `1.7.0-1.9.20-Beta2` everything continues to build.

Did something get messed up when publishing the Gradle Plugin v1.8.1?

**Comment by Foso** [comment]
Thank you for reporting this. Yes, something messed up. The 1.8.1 does not contains the fix for Kotlin 1.9.20. 
I just uploaded the correct version of the compiler plugin (1.8.2) . 
As a workaround you can set the version to the Ktorfit Gradle extension. Then it will use the correct compiler plugin.

```
ktorfit{
    version = "1.8.2"
}
```

I'm planning to release a new Ktorfit version that will remove the warnings in the generated Code at the weekend.
