### ISSUE TITLE
Automatic koin definitions

### ISSUE THREAD

**Issue by dshatz** [Foso/Ktorfit#544]
**Is your feature request related to a problem? Please describe.**
We have a lot of ktorfit service interfaces. We would like to add them all to a koin module without mentioning them one by one with `create()` and `@Single` annotations.

**Describe the solution you'd like**
Not sure how easy it is, but in an ideal world maybe ktorfit could optionally generate a koin module out of all services. 

**Describe alternatives you've considered**
Binding each service manually.

**Additional context**
Please point me in the right direction if there is a good solution already.

**Comment by Foso** [comment]
Hi @dshatz , thank you for using Ktorfit and for sending your idea. I don't think that feature should be included into Ktorfit, because Ktorfit can also be used without Koin. I don't want to make sure that Ktorfit always generates the latest syntax of defining Koin modules.

You could solve your issue by writing your own KSP plugin which will generate the Koin modules.  I think it's doable without too much code

**Comment by dshatz** [comment]
https://github.com/dshatz/ktorfit-koin

Indeed, wasn't a lot of code.

**Comment by Foso** [comment]
Awesome ❤️
