### ISSUE TITLE
How to specify Ktorfit compile-plugin version in 2.0.0

### ISSUE THREAD

**Issue by OSemenovBoyarka** [Foso/Ktorfit#615]
Hey. I'm trying to use Ktorfit `2.0.0` with RC versions of Kotlin - `2.0.10-RC`. However, I get an error about `ktorfit:compiler-plugin ` can't be found:
```
Execution failed for task ':common:compileReleaseKotlinAndroid'.
> Could not resolve all dependencies for configuration ':common:kotlinCompilerPluginClasspathAndroidRelease'.
   > Could not find de.jensklingenberg.ktorfit:compiler-plugin:2.0.0-2.0.10-RC.
```

Look like gradle tries to find compiler plugin with the pattern `<ktorfit-version>-<kotlin-version>`. 
In the maven I can see only version of compiler plugin 2.0.0-2.0.0.

Is there a way to force version of compiler-plugin?

**Comment by alaegin** [comment]
The same issue for 2.0.20-RC

@Foso What can be done?

**Comment by Foso** [comment]
Hi, there is no way to force the version. The problem is that the compiler plugin is still not stable and every new Kotlin version can introduce breaking changes. So i need to release a new version for every new Kotlin version. 

Ktorfit 2.0.1 is now compatible with 2.0.20 https://github.com/Foso/Ktorfit/blob/master/docs/CHANGELOG.md#compilerplugin

**Comment by maicol07** [comment]
@Foso stable 2.0.20 is out. Can you add this version as well?

Thanks
