### ISSUE TITLE
[Bug]: Using @Body requires content-type header to be explicitly set

### ISSUE THREAD

**Issue by Philio** [Foso/Ktorfit#94]
### Ktorfit version

1.0.0-beta16

### What happened and how can we reproduce this issue?

Ktor client configured with JSON content negotiation

Example:

    @POST("auth/verify")
    suspend fun verify(@Body verifyRequest: VerifyRequest)

Error:

java.lang.IllegalStateException: Fail to prepare request body for sending. 
The body type is: class *.VerifyRequest (Kotlin reflection is not available), with Content-Type: null.
    
If you expect serialized body, please check that you have installed the corresponding plugin(like `ContentNegotiation`) and set `Content-Type` header.

### What did you expect to happen?

Content type to be automatically determined based on client configuration (same as Retrofit)

### Is there anything else we need to know about?

Works if the header is set:

    @POST("auth/verify")
    suspend fun verify(@Body verifyRequest: VerifyRequest, @Header("Content-Type") contentType: String = "application/json")

**Comment by DATL4G** [comment]
Retrofit doesn't really recommend this itself, **FOR A GOOD REASON**.

The recommended way to set it in Retrofit looks like this:

```kotlin
@POST("/example/path")
fun example(@Body body: RequestBody)

fun postExample() {
    val body = jsonBuilder.encodeToString(model).toRequestBody("application/json".toMediaType())
    example(body)
}
```

## Why is the current implementation better?

Simple example, lets say we have two API endpoints.
Endpoint 1 for positng info **(requires json)**
Endpoint 2 for posting info **(requires xml)**

Since we need both (json, xml) negotiations, we have installed both in our Ktor instance.
But Ktorfit cannot auto-determine which negotiation type is needed for which endpoint.

### Main problem

So the main problem here is we don't know what type the body actually is.
Even if only one negotiation type is installed we could have another endpoint that requires plain text.

**There is basically no way to check which endpoint needs which content type** and setting this little header yourself isn't that hard, is it?

**Comment by Philio** [comment]
Yeah, that's an option for Retrofit, but I'm referring more to the classic example (which is also on their homepage) where if you have something like:

    @POST("/whatever")
    fun saveSomething(@Body body: Something)

AND you have specified a JSON converter in your Retrofit builder, then you don't need to specify the header.

However, the Ktor architecture is different and as the JSON plugin is a Ktor thing and not a Ktorfit thing, in hindsight,  this is probably not relevant to this library.

Using `@Headers` works fine as well and is a bit cleaner than the original example.

Multiple content types is another matter entirely, you wouldn't usually see this from a single API (and could argue that an API implemented in such a way is not good practice either as it doesn't present a consistent interface to clients). An easier way to get round such an occurrence with Retrofit would be to simply separate JSON/XML endpoints into separate service interfaces and configure separate Retrofit instances with the appropriate converters.

Anyway, this is really a non-issue, I'll close it.
